from fastapi import APIRouter

router = APIRouter(tags=["courses"])

COURSES = {
    "implantologia-avanzada": {
        "id": "implantologia-avanzada",
        "title": "Implantología Avanzada",
        "subtitle": "Técnicas quirúrgicas y protéticas de vanguardia",
        "category": "long",
        "duration": "6 meses",
        "hours": 120,
        "modality": "Presencial + Online",
        "price": "$3,500",
        "spots": 15,
        "image": "implantologia",
        "description": "Programa integral de implantología que abarca desde la planificación digital hasta la carga inmediata. Incluye prácticas en modelos simuladores y casos clínicos reales.",
        "objectives": [
            "Dominar la planificación digital con CBCT y software de diseño",
            "Realizar técnicas de injerto óseo y elevación de seno maxilar",
            "Implementar protocolos de carga inmediata",
            "Gestionar complicaciones y fracasos implantológicos",
        ],
        "modules": [
            {"name": "Diagnóstico y Planificación Digital", "weeks": 3},
            {"name": "Cirugía de Injertos Óseos", "weeks": 4},
            {"name": "Elevación de Seno Maxilar", "weeks": 3},
            {"name": "Carga Inmediata y Protocolos", "weeks": 4},
            {"name": "Rehabilitación Protética sobre Implantes", "weeks": 4},
            {"name": "Complicaciones y Mantenimiento", "weeks": 2},
        ],
        "instructor": "Dr. Carlos Mendoza",
        "rating": 4.9,
        "students": 87,
    },
    "endodoncia-microscopica": {
        "id": "endodoncia-microscopica",
        "title": "Endodoncia Microscópica",
        "subtitle": "Precisión y éxito en tratamientos de conductos",
        "category": "long",
        "duration": "4 meses",
        "hours": 80,
        "modality": "Presencial",
        "price": "$2,800",
        "spots": 12,
        "image": "endodoncia",
        "description": "Especialización en endodoncia con uso de microscopio operatorio. Aprende a resolver casos complejos con técnicas modernas y tecnología de punta.",
        "objectives": [
            "Manejar el microscopio operatorio en endodoncia",
            "Localizar y tratar conductos adicionales",
            "Realizar retratamientos endodónticos complejos",
            "Dominar las técnicas de obturación tridimensional",
        ],
        "modules": [
            {"name": "Fundamentos de Microscopía Clínica", "weeks": 2},
            {"name": "Anatomía Interna y Localización de Conductos", "weeks": 3},
            {"name": "Instrumentación Avanzada", "weeks": 3},
            {"name": "Obturación Tridimensional", "weeks": 2},
            {"name": "Retratamientos y Cirugía Periapical", "weeks": 4},
        ],
        "instructor": "Dra. María Fernanda López",
        "rating": 4.8,
        "students": 64,
    },
    "ortodoncia-invisible": {
        "id": "ortodoncia-invisible",
        "title": "Ortodoncia Invisible",
        "subtitle": "Alineadores transparentes: diagnóstico y tratamiento",
        "category": "long",
        "duration": "5 meses",
        "hours": 100,
        "modality": "Híbrida",
        "price": "$3,200",
        "spots": 20,
        "image": "ortodoncia",
        "description": "Domina el diseño y la planificación de tratamientos con alineadores transparentes. Desde el escaneo digital hasta el seguimiento del caso completo.",
        "objectives": [
            "Realizar diagnóstico cefalométrico digital",
            "Diseñar planes de tratamiento con software especializado",
            "Gestionar el workflow digital completo",
            "Resolver casos complejos con alineadores",
        ],
        "modules": [
            {"name": "Diagnóstico Digital y Cefalometría", "weeks": 3},
            {"name": "Escaneo Intraoral y Modelos 3D", "weeks": 2},
            {"name": "Planificación de Tratamiento Digital", "weeks": 4},
            {"name": "Técnicas de Alineamiento Avanzadas", "weeks": 4},
            {"name": "Seguimiento y Ajustes Clínicos", "weeks": 3},
        ],
        "instructor": "Dr. Andrés Villanueva",
        "rating": 4.7,
        "students": 52,
    },
    "fotografia-dental": {
        "id": "fotografia-dental",
        "title": "Fotografía Clínica Dental",
        "subtitle": "Documentación visual profesional",
        "category": "short",
        "duration": "2 días",
        "hours": 16,
        "modality": "Presencial",
        "price": "$450",
        "spots": 20,
        "image": "fotografia",
        "description": "Workshop intensivo de fotografía clínica. Aprende a capturar imágenes profesionales para documentación, comunicación con el laboratorio y marketing.",
        "objectives": [
            "Configurar equipo fotográfico para clínica dental",
            "Dominar protocolos de toma de fotografías clínicas",
            "Editar y presentar casos documentados",
            "Usar la fotografía como herramienta de marketing",
        ],
        "modules": [
            {"name": "Equipamiento y Configuración", "weeks": 0},
            {"name": "Protocolos de Toma Clínica", "weeks": 0},
            {"name": "Edición y Presentación", "weeks": 0},
        ],
        "instructor": "Dr. Roberto Iglesias",
        "rating": 4.9,
        "students": 134,
    },
    "blanqueamiento-avanzado": {
        "id": "blanqueamiento-avanzado",
        "title": "Blanqueamiento Avanzado",
        "subtitle": "Técnicas modernas para sonrisas radiantes",
        "category": "short",
        "duration": "1 día",
        "hours": 8,
        "modality": "Presencial",
        "price": "$280",
        "spots": 25,
        "image": "blanqueamiento",
        "description": "Curso intensivo sobre las últimas técnicas de blanqueamiento dental. Desde el diagnóstico del color hasta protocolos de mantenimiento a largo plazo.",
        "objectives": [
            "Diagnosticar y clasificar alteraciones del color",
            "Seleccionar la técnica de blanqueamiento adecuada",
            "Manejar sensibilidad dental post-blanqueamiento",
            "Establecer protocolos de mantenimiento",
        ],
        "modules": [
            {"name": "Diagnóstico del Color", "weeks": 0},
            {"name": "Técnicas de Blanqueamiento", "weeks": 0},
            {"name": "Manejo de Sensibilidad", "weeks": 0},
        ],
        "instructor": "Dra. Laura Castillo",
        "rating": 4.8,
        "students": 210,
    },
    "emergencias-dentales": {
        "id": "emergencias-dentales",
        "title": "Emergencias Dentales",
        "subtitle": "Manejo urgente en la práctica diaria",
        "category": "short",
        "duration": "1 día",
        "hours": 8,
        "modality": "Online",
        "price": "$200",
        "spots": 30,
        "image": "emergencias",
        "description": "Capacítate en el manejo de urgencias dentales. Aprende protocolos de actuación rápida para trauma dental, hemorragias, infecciones agudas y dolor severo.",
        "objectives": [
            "Aplicar protocolos de actuación en trauma dental",
            "Manejar hemorragias post-quirúrgicas",
            "Diagnosticar y tratar infecciones agudas",
            "Gestionar dolor odontológico severo",
        ],
        "modules": [
            {"name": "Trauma Dental Avulsionario", "weeks": 0},
            {"name": "Hemorragias y Control", "weeks": 0},
            {"name": "Infecciones Agudas", "weeks": 0},
        ],
        "instructor": "Dr. Javier Morales",
        "rating": 4.6,
        "students": 175,
    },
    "carillas-ceramicas": {
        "id": "carillas-ceramicas",
        "title": "Carillas Cerámicas",
        "subtitle": "Estética dental con resultados predecibles",
        "category": "short",
        "duration": "3 días",
        "hours": 24,
        "modality": "Presencial",
        "price": "$650",
        "spots": 15,
        "image": "carillas",
        "description": "Workshop práctico sobre diseño, preparación y colocación de carillas cerámicas. Incluye taller hands-on con modelos y simulación clínica.",
        "objectives": [
            "Diseñar sonrisas con criterios estéticos digitales",
            "Realizar preparaciones mínimamente invasivas",
            "Seleccionar materiales cerámicos adecuados",
            "Protocolos de cementación adhesiva",
        ],
        "modules": [
            {"name": "Diseño de Sonrisa Digital", "weeks": 0},
            {"name": "Preparación y Provisionales", "weeks": 0},
            {"name": "Cementación Adhesiva", "weeks": 0},
        ],
        "instructor": "Dra. Ana Lucía Reyes",
        "rating": 4.9,
        "students": 98,
    },
    "periodoncia-avanzada": {
        "id": "periodoncia-avanzada",
        "title": "Periodoncia Quirúrgica",
        "subtitle": "Técnicas regenerativas y estéticas gingivales",
        "category": "long",
        "duration": "5 meses",
        "hours": 90,
        "modality": "Presencial",
        "price": "$3,100",
        "spots": 12,
        "image": "periodoncia",
        "description": "Programa avanzado en cirugía periodontal. Aprende técnicas de regeneración ósea, injertos de tejido blando y cirugía mucogingival estética.",
        "objectives": [
            "Realizar cirugía de colgajo con técnicas regenerativas",
            "Ejecutar injertos de tejido conectivo y libre de encía",
            "Dominar la cirugía mucogingival estética",
            "Planificar tratamientos periodontales integrales",
        ],
        "modules": [
            {"name": "Diagnóstico Periodontal Avanzado", "weeks": 2},
            {"name": "Cirugía Resectiva", "weeks": 3},
            {"name": "Regeneración Ósea Guiada", "weeks": 4},
            {"name": "Injertos de Tejido Blando", "weeks": 4},
            {"name": "Cirugía Mucogingval Estética", "weeks": 3},
        ],
        "instructor": "Dr. Fernando Ríos",
        "rating": 4.8,
        "students": 43,
    },
}


@router.get("/courses")
async def list_courses(category: str | None = None):
    result = list(COURSES.values())
    if category:
        result = [c for c in result if c["category"] == category]
    return result


@router.get("/courses/{course_id}")
async def get_course(course_id: str):
    course = COURSES.get(course_id)
    if not course:
        from fastapi import HTTPException
        raise HTTPException(status_code=404, detail="Course not found")
    return course
